version: "3"

tasks:
  cp-camera:
    cmds:
      - |
        scp -r src/camera camera-pi.ts:/home/comitup/pixel-pulse/src/
    silent: True

  cp-camera-plib:
    # args:
    #   - name: registry
    #     desc: Description of arg1 (optional)
    #     required: false
    cmds:
      - |
        scp -r ../polite-lib/src camera-pi.ts:/home/comitup/polite-lib
    silent: True

  mirror:
    cmds:
      - |
        mc mirror --watch a1/photos/raw_photos/{{.CLI_ARGS}} data/{{.CLI_ARGS}}

  gen-vid:
    cmds:
      - |
        python3.10 src/camera/generate-video.py {{.CLI_ARGS}} -o
